### ISSUE TITLE
No error messages displayed when using hide_confirm in select_multiple

### ISSUE THREAD

**Issue by provinzkraut** [Kamik423/cutie#10]
When using `select_multiple` with `hide_confirm=True`, no error messages are displayed.

The issue lies [here](https://github.com/Kamik423/cutie/blob/master/cutie.py#L199) and could be solved by altering the message in a seperate `if hide_confirm` branch and then printing it, instead of putting the complete message printing in a `if hide_confirm` branch.

**Comment by Kamik423** [comment]
Closed by https://github.com/Kamik423/cutie/commit/8cf3dfd58d5562ddef0c1fd236674c7453c7568c
