### ISSUE TITLE
Consistency in select_mutiple when using maximal_count / minimal_count

### ISSUE THREAD

**Issue by provinzkraut** [Kamik423/cutie#11]
When using `select_multiple` with `minimal_count=True`, trying to confirm when too few options are selected results in an error being displayed.

However, when using `maximal_count=True` it is not possible to select more options than allowed.

It should be possible to select more options than allowed and display an error message when trying to confirm, to be consistent to `minimal_count=True`.
Alternatively a message could be flashed when the user tries to select an option, but `maximal_count` is reached. This way a user would at least get some feedback.

Apart from that, this means theres some unreachable code [here](https://github.com/Kamik423/cutie/blob/master/cutie.py#L227-L228) and [there](https://github.com/Kamik423/cutie/blob/master/cutie.py#L245-L246).

**Comment by Kamik423** [comment]
Should be solved by https://github.com/Kamik423/cutie/commit/6fdfd2a709393fd7eb7bd9695fa1bff1d9956a3b. You can now select as many or as few options as you would like. It will just stop you when you try to confirm.
