### ISSUE TITLE
Unresponsivness when using select_multiple with minimal_count and hide_confirm

### ISSUE THREAD

**Issue by provinzkraut** [Kamik423/cutie#12]
Using `select_multiple` with `minimal_count` and `hide_confirm=True` leads to unresponsivness.

When trying to confirm, the user isn't prompted with a feedback and the state just doesn't change.
Keyboard interrupt via `CTRL + C` doesn't work either, the CLI is just unresponsive until the right amount of options are selected

Code to repoduce the issue:
`cutie.select_multiple(["foo", "bar"], minimal_count=1, hide_confirm=True)`

**Comment by provinzkraut** [comment]
I just noticed that `CTRL + C `doesn't work at all when using `minimal_count` while the requirements are not met

**Comment by Kamik423** [comment]
I just created a new branch https://github.com/Kamik423/cutie/tree/consistency. The first commit in it, https://github.com/Kamik423/cutie/commit/8e89baf54498cc83821d3a9a0b9147279d745046 (Default key list), should take care of at least `CTRL + C` in this case.
