### ISSUE TITLE
caption indices not available in pip3 verision

### ISSUE THREAD

**Issue by kdggavkc** [Kamik423/cutie#15]
When pip3 installing cutie, the version of cutie that is installed is cutie-0.2.1 

The select function in this version does not have an argument for caption indices:

```python
def select(
        options: List[str],
        deselected_prefix: str = '\033[1m[ ]\033[0m ',
        selected_prefix: str = '\033[1m[\033[32;1mx\033[0;1m]\033[0m ',
        selected_index: int = 0) -> int:
    """Select an option from a list.

    Args:
        options (List[str]): The options to select from.
        deselected_prefix (str, optional): Prefix for deselected option ([ ]).
        selected_prefix (str, optional): Prefix for selected option ([x]).
        selected_index (int, optional): The index to be selected at first.

    Returns:
        int: The index that has been selected.
    """
    print('\n' * (len(options) - 1))
    while 1:
        print(f'\033[{len(options) + 1}A')
        for i, option in enumerate(options):
            print('\033[K{}{}'.format(
                selected_prefix if i == selected_index else deselected_prefix,
                option))
        keypress = readchar.readkey()
        if keypress == readchar.key.UP:
            selected_index = max(selected_index - 1, 0)
        elif keypress == readchar.key.DOWN:
            selected_index = min(selected_index + 1, len(options) - 1)
        else:
            break
    return selected_index
```

Are there plans to distribute the version of cutie that has the features as the example in the readme? I like the caption indices feature but currently do not have access to it.

**Comment by kdggavkc** [comment]
I do not believe this fixed it -- though I am able to install cutie 2.2, I still receive this error, and the function appears unchanged from the copy and paste above. 

```
Traceback (most recent call last):
  File "app.py", line 59, in <module>
    ProjectSelect()
  File "app.py", line 40, in __init__
    command(self)
  File "app.py", line 54, in EditExisting
    cutie.select(options, caption_indices=caption_indices)
TypeError: select() got an unexpected keyword argument 'caption_indices'

```

**Comment by Kamik423** [comment]
I am so sorry this is such a huge inconvenience for you!

Could you please do:

```bash
pip3 install --upgrade --no-cache -I cutie
```

And paste the output from pip here? (If it still does not work then)

**Comment by kdggavkc** [comment]
No sweat @Kamik423 - happy to help:
```

kdggavkc@far-madding:~/Code/jungle/ritual$ pip3 install --upgrade --no-cache -I cutie
Collecting cutie
  Downloading https://files.pythonhosted.org/packages/79/1d/f8389619189b3de32f66be40cc7d17d6d2c06e35bbd21f6869120bd912b3/cutie-0.2.2-py3-none-any.whl
Collecting readchar (from cutie)
  Downloading https://files.pythonhosted.org/packages/ef/f3/50cc9199733bf91f3c140150752a6430d8b785f9d22a31dcae721edb0b9a/readchar-2.0.1-py3-none-any.whl
Collecting colorama (from cutie)
  Downloading https://files.pythonhosted.org/packages/0a/93/6e8289231675d561d476d656c2ee3a868c1cca207e16c118d4503b25e2bf/colorama-0.4.0-py2.py3-none-any.whl
Installing collected packages: readchar, colorama, cutie
Successfully installed colorama-0.4.0 cutie-0.2.2 readchar-2.0.1

```

**Comment by Kamik423** [comment]
The file downloaded for cutie does not contain the erroneous files. Does it still happen? Or did this latest install fix it?

**Comment by kdggavkc** [comment]
From where I stand, the select statement is unchanged from the original post. You are unable to replicate?

**Comment by kdggavkc** [comment]
The cutie.py file in this repo is what was bdist_wheeled and twined?

**Comment by Kamik423** [comment]
No. When I downloaded PyPI version 2.1 it was broken the way you described. After upgrading to 2.2 it was fixed.

Can you do

```bash
pip3 show cutie
```

and take a look at the directory listed as `Location` (in my case `/usr/local/lib/python3.7/site-packages`) and tell me what things in there are named `cutie` (directories / `.py` files / ...).

Are you using virtual environments?

----

Concerning the question:

```bash
python setup.py sdist bdist_wheel
twine upload dist/*
```

**Comment by kdggavkc** [comment]
```
kdggavkc@far-madding:~/Code/jungle$ pip3 show cutie
Name: cutie
Version: 0.2.2
Summary: Commandline User Tools for Input Easification
Home-page: https://github.com/kamik423/cutie
Author: Hans
Author-email: contact.kamik423@gmail.com
License: MIT
Location: /home/kdggavkc/.local/lib/python3.6/site-packages
Requires: colorama, readchar

```

Should I be on Python 3.7?

**Comment by Kamik423** [comment]
Python 3.6 should work just fine. I am on 3.7.

Can you go to `/home/kdggavkc/.local/lib/python3.6/site-packages` and search for cutie?

**Comment by kdggavkc** [comment]
Yes - in that location there are:

cutie (directory)
cutie.py (this contains the version of select I would like)
cutie-0.2.1.dist-info (directory)
cutie-0.2.2.dist-info (directory

**Comment by kdggavkc** [comment]
@Kamik423 I have deleted all of those and ran your original suggested statement, and that has worked. Apologies for the difficulty.

**Comment by kdggavkc** [comment]
But thank you for the help

**Comment by Kamik423** [comment]
Digging around a bit, I found [this](https://github.com/pypa/pip/issues/5020).
When upgrading cutie the from `0.2.1` to `0.2.2` did you use the `-I` or `--ignore-installed` option?

I want to prevent this for other users.

**Comment by kdggavkc** [comment]
@Kamik423 I did not pass those flags

**Comment by Kamik423** [comment]
This is weird. But the issue is resolved now and I know what to do, should it happen to other users.

Thank you for your help!

**Comment by kdggavkc** [comment]
I suspect it could be that my import was prioritizing a different build than what I had installed, even though I had uninstalled the older version.

**Comment by Kamik423** [comment]
A part of it is, that it is somehow possible to upgrade to `0.2.2` without deleting the old package, because it only contains a module. This only happens for me with the `-I` option. With the "regular" upgrade it gets removed correctly for me.
