### ISSUE TITLE
A possible release of dev branch

### ISSUE THREAD

**Issue by chfw** [Kamik423/cutie#24]
Hi @Kamik423 

Cutie v0.2.2 do not allow user to quit multiple selection function. And the KeyboardInterrupt support in all three functions are not released but in dev branch. Do you have any plans to release your dev branch? 

Thanks

**Comment by C0D3D3V** [comment]
I also just included cutie in my project. I think with this one file it doesn't matter either. But it would be really nice if the `dev` branch would be named `master` because the version is much better. I think so far you can just include the git project as a submodule or just copy the file.

**Comment by C0D3D3V** [comment]
Oh, I can just see that already happened, if I'm not mistaken. Well then it's all about the release.

**Comment by chfw** [comment]
I have included it in my project but obviously, embedding is not a good choice.
