### ISSUE TITLE
small things

### ISSUE THREAD

**Issue by jabbalaci** [Kamik423/cutie#4]
Very nice project! Some small remarks:
* instead of `while 1` use `while True` for an infinite loop
* the folder `__pycache__` shouldn't be on GitHub; put it in `.gitignore`

Update: when you create a new repo, you can select the language and GitHub offers to create a `.gitignore` file for you. The default `.gitignore` for Python is quite long and includes `__pycache__`.
Update 2: a `requirements.txt` would be nice too if someone wants to download and install it in a virtual environment.

**Comment by dherrada** [comment]
Just added those suggestions to my pr

**Comment by Kamik423** [comment]
Closed by 
https://github.com/Kamik423/cutie/commit/37989055bac2b216aa1c65abffb76c87c85087b3, 
https://github.com/Kamik423/cutie/commit/a5438d7b6596b91e998c8ce928d57eac716d6e89 and 
https://github.com/Kamik423/cutie/commit/b35c079f5c7f4e174374fd6c3ba6c3d63e0e3e7c
