### ISSUE TITLE
Don't exit on unrecognized keys

### ISSUE THREAD

**Issue by provinzkraut** [Kamik423/cutie#7]
Functions like `select` will exit the CLI if an unrecognized key is pressed.
Because of this, `select` not only will exit on `ENTER`, but also on any other key that is not `UP` or `DOWN`. This could be potentially be frustrating if the user is 10 sections down in a dialog and has to start over again, just because he pressed `RIGHT` instead of `UP`.

I suggest to just ignore these inputs and only react to the available options.

**Comment by dherrada** [comment]
Just made the pr

**Comment by dherrada** [comment]
*added it to my pr

**Comment by provinzkraut** [comment]
The issue is not only within `select`, but also `select_mutiple`, and `prompt_yes_or_no`. 
And for consitency it would be great to allways accept the same options to exit (`prompt_yes_or_no` listens for `CTRL + C` and `CTRL + D`).

Also it would be nice if you could make a seperate pull request for these features, so it's easier to identifiy and manage.

**Comment by dherrada** [comment]
How exactly do I do that, whenever I push it, it just adds to my pr. Sorry. I'm pretty new to git.

**Comment by Kamik423** [comment]
I also am no expert. But googling around a bit ([#1](https://meta.discourse.org/t/pull-requests-how-to-properly-submit-multiple-requests/19401), [#2](https://www.quora.com/Is-there-a-good-system-for-adding-multiple-pull-requests-to-GitHub)) it seems like you have to [create separate branches](https://www.atlassian.com/git/tutorials/using-branches) and create a pull request for each branch.

**Comment by provinzkraut** [comment]
I think invalid input should be ignored, and never crash or take it as confirmation.
As I said, it could be potentially be very frustrating if the CLI just crashes if you accidently use `LEFT` instead of `DOWN`. This can happen very easily.

It would also be good if the confirmation key was the same for every function.
Confirming with `ENTER` (as it is the default in every CLI) in `get_number` but using `ENTER` for selecting an option in `select_multiple` is confusing, and as I said in #9, this differs from the default option in most CLIs, where `ENTER` is confirm, and `SPACE` is select.

A compromise would be:

Terminate on `CTRL + C` or user defined terminate keys
Display dialog to confirm exit on unknown key
Confirm with `ENTER` or user defined confirmation keys

**Comment by Kamik423** [comment]
I would always at least allow `ENTER` as confirmation, except for `select_multiple`. For example I think there is no harm in allowing it to confirm `select`.

How do you imagine "*user defined terminate keys*" being specified? Should they be passed as argument to each function or should they be set for the entire module somehow?

**Comment by provinzkraut** [comment]
Yes, like I said: `ENTER` should allways confirm ;)
But it should be consistent amongst all functions. 

As for now it could be done on per-function basis.
Ideally the interface would be wrapped in a class where default options could be set.

**Comment by Kamik423** [comment]
However should `SPACE` confirm in `select` where a confirmation and a selection are identical?

**Comment by provinzkraut** [comment]
This is a question of style.
Personally I'd prefer if that would be to different actions. 

Maybe add a `confirm_on_select` option or something like that.
But by default selection should select and confirm should confirm ;)

**Comment by Kamik423** [comment]
Also, thinking about it, when using arrow keys to navigate, would it make sense for right arrow key to confirm or select?

It currently does in `prompt_yes_or_no`, where left arrow key also functions as backspace.

[![comic](http://angriestprogrammer.com/comics/code_idiots.png)](http://angriestprogrammer.com/comic/code_idiots)

**Comment by Kamik423** [comment]
The original issue (Don't exit on unrecognized keys) should be resolved in the first commit 
https://github.com/Kamik423/cutie/commit/8e89baf54498cc83821d3a9a0b9147279d745046 of the new branch [consistency](https://github.com/Kamik423/cutie/tree/consistency). Its main feature is having default key lists, like a list of confirmation keys or a list of up keys:

```python
class DefaultKeys:
    """List of default keybindings.
    Attributes:
        interrupt(List[str]): Keys that cause a keyboard interrupt.
        select(List[str]): Keys that trigger list element selection.
        confirm(List[str]): Keys that trigger list confirmation.
        delete(List[str]): Keys that trigger character deletion.
        down(List[str]): Keys that select the element below.
        up(List[str]): Keys that select the element above.
    """
    interrupt: List[str] = [readchar.key.CTRL_C, readchar.key.CTRL_D]
    select: List[str] = [readchar.key.SPACE]
    confirm: List[str] = [readchar.key.ENTER]
    delete: List[str] = [readchar.key.BACKSPACE]
    down: List[str] = [readchar.key.DOWN, 'j']
    up: List[str] = [readchar.key.UP, 'k']
```

It furthermore adds [the `confirm_on_select` parameter](https://github.com/Kamik423/cutie/issues/7#issuecomment-439527949) to `select` which defaults to `True`.

It also removes all use of left and right arrow keys.

**Comment by provinzkraut** [comment]
I will look into that.

But wouldn't it be better to just wrap all the cutie functions in a `Cutie` class and to the configuration there?

Changing attributes in a module level class isn't really user friendly, intuitive, stable or pythonic..
And when you have a `Cutie` class, you could have multiple objects with different configurations, that could come in handy.

I'll try to catch up with the tests at the moment ;)

Although I like the idea of switching selection state with left/right arrows.
