### ISSUE TITLE
Make hide_confirm the default in select_multiple

### ISSUE THREAD

**Issue by provinzkraut** [Kamik423/cutie#9]
One key should represent one action, and having the tick action bound to `ENTER` and `SPACE` is redundant, plus it is a few extra steps to confirm input. 

Selecting with `SPACE` and confirming with `ENTER` is more intuitive and faster, so i think this should be the default option.

**Comment by Kamik423** [comment]
My reasoning for this was:

It is (in my opinion) more intuitive to have `ENTER` for confirmation. It is more similar to what we are used to from graphical interfaces. For example when I select from the (single) `select` list I use `ENTER`. The confirm button also is more straight forward. A new user encountering the `select_multiple` for the first time would probably not know what to do, try `ENTER` and confirm the menu. An explanation would have to be added every time like  "`SPACE to select, ENTER to confirm`", which in my opinion is less elegant.

Concerning redundancy: [as requested on Reddit](https://www.reddit.com/r/Python/comments/9x1smv/comment/e9potg8/?st=JOI6UKD9&sh=f26f0ebd) I wanted to add vim shortcuts that (for better or worse) are used by many people and supported by many interfaces.

What do you think?

**Comment by dherrada** [comment]
To add on to what Kamik423 said, if you don't want `ENTER` to tick, set `hide_confirm` to `True` and then you can select with space and submit with enter
